server:
  port: ${SECURITY_SERVICE_PORT}
  servlet:
    context-path: ${SERVER_PATH}

eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true

    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI} 

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}

    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    loadbalancer.ribbon.enabled: false  

  liquibase:
    change-log: classpath:db/changelog/changelog-main.yaml


logging:
  level:
    ru.manannikov.filesharingservice.securityservice: DEBUG


app:
  security:
    jwt:
      key: ${JWT_SECRET_KEY}
      # algorithm: HS256
      access-key-expiration-time: 60m
      refresh-key-expiration-time: 2d


springdoc:
  swagger-ui:
    enabled: true
    path: ${SWAGGER_UI_PATH}

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
