server:
#  port: 8071
  port: ${GATEWAY_SERVER_PORT}


eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true

    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI} 


spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
      # lb -> load balancer
      # Просто идентификатор роута
      - id: file-sharing-s3-service
        # Идентификатор сервиса, зарегистрированного в eureka
        uri: lb://file-sharing-s3-service
        predicates:
        - Path=/s3/**

        filters:
        - RewritePath=/s3/(?<path>.*), /$\{path}
        - PrefixPath=/api/v1

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true

    health:
      show-details: always