server:
#  port: 8071
  port: ${GATEWAY_SERVER_PORT}


eureka:
  instance:
    preferIpAddress: true

  client:
    registerWithEureka: true
    fetchRegistry: true

    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI} 


spring:
  main: 
    web-application-type: reactive
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
      # lb -> load balancer
      # Просто идентификатор роута
      - id: file-sharing-s3-buckets
        # Идентификатор сервиса, зарегистрированного в eureka
        uri: lb://file-sharing-s3-service
        predicates:
        - Path=/s3/bucket/**,/bucket/**

        filters:
        - RewritePath=/(?:s3/)?bucket/(?<path>.*), /$\{path}
        - AuthorizationFilter=MANAGE_BUCKETS
        - PrefixPath=/api/v1/bucket


      - id: file-sharing-s3-objects
        # Идентификатор сервиса, зарегистрированного в eureka
        uri: lb://file-sharing-s3-service
        predicates:
        - Path=/s3/object/**,/object/**

        filters:
        - RewritePath=/(?:s3/)?object/(?<path>.*), /$\{path}
        - AuthorizationFilter=MANAGE_OBJECTS
        - PrefixPath=/api/v1/object


      - id: file-sharing-authentication-service
        uri: lb://file-sharing-security-service
        predicates:
        - Path=/auth/**

        filters:
        - PrefixPath=/api/v1


app:
  security:
    jwt:
      key: ${JWT_SECRET_KEY}

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true

    health:
      show-details: always


logging:
  level:
    ru.manannikov.filesharingservice.gatewayserver: DEBUG